name: checks
on: [pull_request, workflow_dispatch]

env:
  ACT_OWNER: ${{ github.repository_owner }}
  ACT_REPOSITORY: ${{ github.repository }}
  CACHED_DOCKER_IMAGES: '"node:12-buster" "node:12-buster-slim" "ubuntu:18.04" "ubuntu:latest" "alpine:3.10" "tonistiigi/binfmt:latest"'
  CACHED_DOCKER_IMAGES_KEY: docker-images-0
  GO_VERSION: 1.17

jobs:
  check-can-mrege:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate has QA done
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const {data: comments }  = await github.issues.listComments({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const commentQA = comments.find(comment => comment.body.includes("Etapa de E2E Teste"))

          if(commentQA)
            const checks = (!commentQA.body.match(/(\[x])|(\[ ])/gi);
            if(checks.length)
              const marked = checks.join("").match(/x/g).length > 1
              if(marked)
                throw 'Parameter is not a number!';
