name: checks
on:
  pull_request:
    types: [opened]

env:
  ACT_OWNER: ${{ github.repository_owner }}
  ACT_REPOSITORY: ${{ github.repository }}
  CACHED_DOCKER_IMAGES: '"node:12-buster" "node:12-buster-slim" "ubuntu:18.04" "ubuntu:latest" "alpine:3.10" "tonistiigi/binfmt:latest"'
  CACHED_DOCKER_IMAGES_KEY: docker-images-0
  GO_VERSION: 1.17

jobs:
  PR-Comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create comment
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const query = `query ($name: String!, $owner: String!, $pull_number: Int!) {
              repository(name: $name, owner: $owner) {
                pullRequest(number: $pull_number) {
                  reviewRequests(last: 10) {
                    nodes {
                      requestedReviewer {
                        ... on User {
                          id
                          email
                          avatarUrl
                          name
                        }
                      }
                    }
                  }
                }
              }
            }`;

          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo,
            pull_number: ${{ github.event.number }}
          }

          const approvalsRequired = await github.graphql(query, variables)
          const reviewers = approvalsRequired.repository.pullRequest.reviewRequests.nodes.map(r => r.requestedReviewer)

          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Etapa de E2E Teste \n\n ${reviewers.map(reviewer => {
              return `- [ ] ${reviewer.name} ${reviewer.email}`
            })`
          })
